// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3588.PowerUp.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3588.PowerUp.Robot;
import org.usfirst.frc3588.PowerUp.RobotMap;

/**
 *
 */
public class newDriveStraight extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_power;
    private double m_time;
    private double m_distance;
    private double gyroReading;
    private double DL = 1.0;
    private double DR = 1.0;
    private boolean ultrasensor;
    private int ElyghsMagicalNumber = 2;
    private double backDrive = -0.2;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public newDriveStraight(double power, double time, double distance) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_power = -0.8 * power;
        m_time = time;
        m_distance = distance;
//        ultrasensor = ultrasonic;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
//    	if (m_power == RobotMap.STOP) {
//    		throw new IllegalArgumentException("Invalid power value " + Double.toString(m_power));
//    	}
    	if (m_time > 0) {
    		setTimeout(m_time);
    	}
//    	if (m_distance != 0) {
//    		//RobotMap.chassisleftMotorEncoder.reset();
//    		RobotMap.chassisrightMotorEncoder.reset();
//    	}
    	RobotMap.chassisGyro.reset();
    	RobotMap.chassisrightMotorEncoder.reset();
    	if (m_distance < 0) {
    		m_power *= -1;
    		backDrive *= -1;
    		
    	}
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
//    	gyroReading = RobotMap.chassisGyro.getAngle();
//    	if (gyroReading > ElyghsMagicalNumber) {
//    		RobotMap.chassisleftMotor.set(m_power);
//        	RobotMap.chassisrightMotor.set(m_power - 0.2);
//        	System.out.println("adjusting right");
//    		
//    	}else if (gyroReading < -ElyghsMagicalNumber) {
//    		
//    		RobotMap.chassisleftMotor.set(m_power - 0.2);
//        	RobotMap.chassisrightMotor.set(m_power);
//        	System.out.println("adjusting left");
//    	}else {
//    		RobotMap.chassisleftMotor.set(m_power);
//        	RobotMap.chassisrightMotor.set(m_power);
//    	}
    	RobotMap.chassisrightMotor.set(m_power);
    	RobotMap.chassisleftMotor.set(m_power);
    	//System.out.println("distance from newdrivestaight :" + Math.abs(RobotMap.chassisrightMotorEncoder.get()));
    	
    	
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	
//    	if (ultrasensor && RobotMap.chassisUltrasonic1.getRangeInches() < 5) {
//    		return true;
//    	}
    	if ((isTimedOut())
				|| (m_distance > 0 && RobotMap.chassisrightMotorEncoder.getDistance() >= m_distance)) {
			return true;
		} 
//    	else {
//			return false;
//		}
    	return (Math.abs(RobotMap.chassisrightMotorEncoder.get()) >= Math.abs(m_distance));
    }
    // Called once after isFinished returns true
    @Override
    protected void end() {
    	System.out.println("Final encoder value: " + RobotMap.chassisrightMotorEncoder.get());
    	RobotMap.chassisleftMotor.set(RobotMap.STOP);
    	RobotMap.chassisrightMotor.set(RobotMap.STOP);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}

